const TYPES = {
    LOADING_DATA: 'LOAD_DATA',
    FETCH_DATA: 'FETCH_DATA',
    LOADED_DATA:'LOADED_DATA',
    LOADED_DATA_SUCCESS: "LOADED_DATA_SUCCESS",
    LOADED_DATA_FAILED: "LOADED_DATA_FAILED",
}

export default TYPES